repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        stages: [commit]
        args: ["--line-length","88"]
  - repo: local
    hooks:
      - id: pytest-on-push
        name: pytest on push
        entry: pytest
        language: system
        pass_filenames: false
        stages: [push]
