name: Deploy to Azure on main
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: "lb-324"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
